-- 领星数据同步

--店铺档案_店铺授权-------------------------------------------------------------------------------------------------------------------------------------------------------------------
drop table if exists sharkbox_merge.lingxing_merchantlist;
create table sharkbox_merge.lingxing_merchantlist(
     data_owner                   varchar(255) COMMENT '数据属主'
    ,seller_id                    varchar(255) COMMENT 'SellerID'
    ,account_name                 varchar(255) COMMENT '账号名称'
    ,store_type                   varchar(255) COMMENT '店铺类型'
    ,store                        varchar(255) COMMENT '店铺'
    ,country                      varchar(255) COMMENT '国家'
    ,email                        varchar(255) COMMENT '邮件配置'
    ,advertisement_authorize      varchar(255) COMMENT '广告授权'
    ,store_authorize              varchar(255) COMMENT '店铺授权'
    ,update_authorize_time        varchar(255) COMMENT '更新授权时间'
    ,store_authorize_time         varchar(255) COMMENT '店铺授权时间'
    ,authorize_abnormal_time      varchar(255) COMMENT '授权异常时间'
    ,synchronous_status           varchar(255) COMMENT '同步状态'
    ,disable_status               varchar(255) COMMENT '禁用状态'
    ,remark                       varchar(255) COMMENT '备注'
    ,create_time                  datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
    ,modify_time                  datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
    ,data_status                  varchar(255) COMMENT '数据状态'
    ,batch_number                 varchar(255) COMMENT '批次号'
    ,execute_log                  varchar(2000) COMMENT '接口执行日志'
    ,PRIMARY KEY(store)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='店铺档案_店铺授权';

--供应商档案_供应商-------------------------------------------------------------------------------------------------------------------------------------------------------------------
drop table if exists sharkbox_merge.lingxing_supplier;
create table sharkbox_merge.lingxing_supplier(
     data_owner                  varchar(255) COMMENT '数据属主'
    ,supplier_create_time        varchar(255) COMMENT '供应商创建时间'
    ,supplier_code               varchar(255) COMMENT '供应商代码'
    ,supplier_name               varchar(255) COMMENT '供应商名称'
    ,associated_warehouse        varchar(255) COMMENT '关联仓库'
    ,level                       varchar(255) COMMENT '级别'
    ,scale                       varchar(255) COMMENT '规模'
    ,contacts                    varchar(255) COMMENT '联系人'
    ,contact_information         varchar(255) COMMENT '联系方式'
    ,qq_wachat                   varchar(255) COMMENT 'QQ/微信'
    ,email                       varchar(255) COMMENT '邮箱'
    ,fax                         varchar(255) COMMENT '传真'
    ,remark                      varchar(255) COMMENT '备注'
    ,url                         varchar(255) COMMENT '网址'
    ,address                     varchar(255) COMMENT '地址'
    ,payment_method              varchar(255) COMMENT '支付方式'
    ,settlement_method           varchar(255) COMMENT '结算方式'
    ,advance_ratio               varchar(255) COMMENT '预付比例'
    ,settlement_period           varchar(255) COMMENT '结算账期'
    ,settlement_description      varchar(255) COMMENT '结算描述'
    ,credit_code                 varchar(255) COMMENT '统一社会信用代码'
    ,receiving_account_1         varchar(255) COMMENT '收款账户名称1'
    ,account_name_1              varchar(255) COMMENT '户名1'
    ,opening_bank_1              varchar(255) COMMENT '开户行1'
    ,account_number_1            varchar(255) COMMENT '账号1'
    ,receiving_account_2         varchar(255) COMMENT '收款账户名称2'
    ,account_name_2              varchar(255) COMMENT '户名2'
    ,opening_bank_2              varchar(255) COMMENT '开户行2'
    ,account_number_2            varchar(255) COMMENT '账号2'
    ,receiving_account_3         varchar(255) COMMENT '收款账户名称3'
    ,account_name_3              varchar(255) COMMENT '户名3'
    ,opening_bank_3              varchar(255) COMMENT '开户行3'
    ,account_number_3            varchar(255) COMMENT '账号3'
    ,follow_person_1             varchar(255) COMMENT '跟进人1'
    ,follow_person_2             varchar(255) COMMENT '跟进人2'
    ,follow_person_3             varchar(255) COMMENT '跟进人3'
    ,follow_person_4             varchar(255) COMMENT '跟进人4'
    ,follow_person_5             varchar(255) COMMENT '跟进人5'
    ,follow_person_6             varchar(255) COMMENT '跟进人6'
    ,follow_person_7             varchar(255) COMMENT '跟进人7'
    ,follow_person_8             varchar(255) COMMENT '跟进人8'
    ,follow_person_9             varchar(255) COMMENT '跟进人9'
    ,follow_person_10            varchar(255) COMMENT '跟进人10'
    ,create_time                 datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
    ,modify_time                 datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
    ,data_status                 varchar(255) COMMENT '数据状态'
    ,batch_number                varchar(255) COMMENT '批次号'
    ,execute_log                 varchar(2000) COMMENT '接口执行日志';
    ,PRIMARY KEY(supplier_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='供应商档案_供应商';

--采购订单_采购单-------------------------------------------------------------------------------------------------------------------------------------------------------------------
drop table if exists sharkbox_merge.lingxing_purchase_product;
create table sharkbox_merge.lingxing_purchase_product(
     id                                  varchar(255) COMMENT '采购单号+明细编码+sku'
    ,group_id                            varchar(255) COMMENT '组id'
    ,data_owner                          varchar(255) COMMENT '数据属主'
    ,purchase_number                     varchar(255) COMMENT '采购单号'
    ,purchase_type                       varchar(255) COMMENT '采购类型'
    ,order_number_1688                   varchar(255) COMMENT '1688订单号'
    ,purchase_status                     varchar(255) COMMENT '采购状态'
    ,purchaser_party                     varchar(255) COMMENT '采购方'
    ,purchase_warehouse                  varchar(255) COMMENT '采购仓库'
    ,quality_testing_type                varchar(255) COMMENT '质检类型'
    ,supplier                            varchar(255) COMMENT '供应商'
    ,purchaser                           varchar(255) COMMENT '采购员'
    ,person_in_charge                    varchar(255) COMMENT '负责人'
    ,document_remarks                    varchar(255) COMMENT '单据备注'
    ,purchase_create_time                varchar(255) COMMENT '创建时间'
    ,order_time                          varchar(255) COMMENT '下单时间'
    ,logistics_provider                  varchar(255) COMMENT '物流商'
    ,logistics_tracking_number           varchar(255) COMMENT '物流单号'
    ,settlement_method                   varchar(255) COMMENT '结算方式'
    ,advance_ratio                       varchar(255) COMMENT '预付比例'
    ,settlement_period                   varchar(255) COMMENT '结算账期'
    ,settlement_description              varchar(255) COMMENT '结算描述'
    ,transactions                        varchar(255) COMMENT '交易方式'
    ,purchase_currency                   varchar(255) COMMENT '采购币种'
    ,exchange_rate                       varchar(30)  COMMENT '汇率'
    ,is_include_tax                      varchar(30) COMMENT '是否含税'
    ,shipping_fee                        varchar(30) COMMENT '运费'
    ,other_expenses                      varchar(30) COMMENT '其它费用'
    ,purchase_amount                     varchar(30) COMMENT '采购金额'
    ,discount_amount                     varchar(30) COMMENT '折扣金额'
    ,amount_paid                         varchar(30) COMMENT '已付金额'
    ,amount_received                     varchar(30) COMMENT '已收金额'
    ,payment_method                      varchar(60) COMMENT '付款方式'
    ,payment_status                      varchar(30) COMMENT '付款状态'
    ,cost_allocation_method              varchar(60) COMMENT '费用分配方式'
    ,product_dimension                   varchar(255) COMMENT '产品维度'
    ,detail_number                       varchar(255) COMMENT '明细编号'
    ,plan_number                         varchar(255) COMMENT '计划编号'
    ,business_identification             varchar(255) COMMENT '业务标识'
    ,style_name                          varchar(255) COMMENT '款名'
    ,spu                                 varchar(255) COMMENT 'SPU'
    ,product_name                        varchar(255) COMMENT '品名'
    ,sku                                 varchar(255) COMMENT 'SKU'
    ,identification_code                 varchar(255) COMMENT '识别码'
    ,label                               varchar(255) COMMENT '标签'
    ,attribute                           varchar(255) COMMENT '属性'
    ,model                               varchar(255) COMMENT '型号'
    ,brand                               varchar(255) COMMENT '品牌'
    ,classification                      varchar(255) COMMENT '分类'
    ,product_material                    varchar(255) COMMENT '产品材质'
    ,shop                                varchar(255) COMMENT '店铺'
    ,fnsku                               varchar(255) COMMENT 'FNSKU'
    ,msku                                varchar(255) COMMENT 'MSKU'
    ,quantity_per_box                    varchar(30) COMMENT '单箱数量'
    ,cases                               varchar(30) COMMENT '箱数'
    ,order_quantity                      varchar(30) COMMENT '采购量'
    ,is_gift                             varchar(30) COMMENT '是否赠品'
    ,unit_price                          varchar(30) COMMENT '单价'
    ,unit_price_including_tax            varchar(30) COMMENT '含税单价'
    ,tax_rate                            varchar(30) COMMENT '税率'
    ,tax_amount                          varchar(30) COMMENT '税额'
    ,total_price_and_tax                 varchar(30) COMMENT '价税合计'
    ,amount_of_money                     varchar(30) COMMENT '金额'
    ,product_remarks                     varchar(255) COMMENT '产品备注'
    ,procurement_warehouse_details       varchar(255) COMMENT '采购仓库（明细）'
    ,wait_arrival_quantity               varchar(255) COMMENT '待到货量'
    ,expected_delivery_time              varchar(255) COMMENT '预计到货时间'
    ,arrival_quantity                    varchar(255) COMMENT '到货量'
    ,not_inspected_yet                   varchar(255) COMMENT '未质检'
    ,quality_inspection_in_progress      varchar(255) COMMENT '质检中'
    ,pending_listing                     varchar(255) COMMENT '待上架'
    ,available_quantity                  varchar(255) COMMENT '可用量'
    ,quantity_of_defective_products      varchar(255) COMMENT '次品量'
    ,return_quantity                     varchar(255) COMMENT '退货量'
    ,exchange_quantity                   varchar(255) COMMENT '换货量'
    ,excessive_receiving_quantity        varchar(255) COMMENT '超量收货量'
    ,end_difference_quantity             varchar(255) COMMENT '结束差异量'
    ,first_delivery_time                 varchar(255) COMMENT '首次到货时间'
    ,last_delivery_time                  varchar(255) COMMENT '最后到货时间'
    ,first_quality_inspection_time       varchar(255) COMMENT '首次质检时间'
    ,create_time                         datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
    ,modify_time                         datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
    ,data_status                         varchar(20)  COMMENT '数据状态'
    ,data_number                         int          COMMENT '单位数据量'
    ,batch_number                        varchar(255) COMMENT '批次号'
    ,sent_status                         varchar(20)  COMMENT '发货单执行状态'
    ,execute_log                         varchar(2000) COMMENT '接口执行日志'
    ,sent_execute_log                    varchar(2000) COMMENT '接口执行日志'
    ,PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='采购订单_采购单_产品信息'
;

--发货档案_发货单_发货计划-------------------------------------------------------------------------------------------------------------------------------------------------------------------
drop table if exists sharkbox_merge.lingxing_shipping_delivery_schedule;
create table sharkbox_merge.lingxing_shipping_delivery_schedule(
     id                                                  varchar(255)  COMMENT '创建批次号+计划编号+SKU'
    ,group_id                                            varchar(255)  COMMENT '组id'
    ,data_owner                                          varchar(255)  COMMENT '数据属主'
    ,create_batch_number                                 varchar(255)  COMMENT '创建批次号'
    ,batch_remarks                                       varchar(255)  COMMENT '批次备注'
    ,plan_number                                         varchar(255)  COMMENT '计划编号'
    ,state                                               varchar(255)  COMMENT '状态'
    ,print_status                                        varchar(255)  COMMENT '打印状态'
    ,factory_direct_delivery                             varchar(255)  COMMENT '工厂直发'
    ,store                                               varchar(255)  COMMENT '店铺'
    ,country                                             varchar(255)  COMMENT '国家'
    ,planned_delivery_time                               varchar(255)  COMMENT '计划发货时间'
    ,mode_of_transport                                   varchar(255)  COMMENT '运输方式'
    ,logistics_provider                                  varchar(255)  COMMENT '物流商'
    ,logistics_channels                                  varchar(255)  COMMENT '物流渠道'
    ,expected_logistics_delivery_time                    varchar(255)  COMMENT '物流预计时效'
    ,expected_delivery_time                              varchar(255)  COMMENT '预计到货时间'
    ,packaging_type                                      varchar(255)  COMMENT '包装类型'
    ,shipment_number_declared                            varchar(255)  COMMENT '货件单号/已申报'
    ,invoice                                             varchar(255)  COMMENT '发货单/已发货'
    ,purchase_plan_number                                varchar(255)  COMMENT '采购计划编号/采购单号'
    ,stock_order_number                                  varchar(255)  COMMENT '备货单号|关联量'
    ,inventory_discrepancy_quantity                      varchar(255)  COMMENT '备货差异量'
    ,msku                                                varchar(255)  COMMENT 'MSKU'
    ,fnsku                                               varchar(255)  COMMENT 'FNSKU'
    ,asin                                                varchar(255)  COMMENT 'ASIN'
    ,father_asin                                         varchar(255)  COMMENT '父ASIN'
    ,product_name                                        varchar(255)  COMMENT '品名'
    ,sku                                                 varchar(255)  COMMENT 'SKU'
    ,is_urgent                                           varchar(255)  COMMENT '是否加急'
    ,one_box_number_pcs                                  varchar(255)  COMMENT '单箱数量（PCS）'
    ,box_number                                          varchar(255)  COMMENT '箱数'
    ,planned_shipment_quantity                           varchar(255)  COMMENT '计划发货量'
    ,total_planned_shipment_quantity                     varchar(255)  COMMENT '总计划发货量'
    ,discrepancy_quantity                                varchar(255)  COMMENT '差异量'
    ,delivery_warehouse                                  varchar(255)  COMMENT '发货仓库'
    ,transit_warehouse                                   varchar(255)  COMMENT '中转仓库'
    ,shipping_warehouse_store                            varchar(255)  COMMENT '发货仓库店铺'
    ,shipping_warehouse_fnsku                            varchar(255)  COMMENT '发货仓库FNSKU'
    ,position_quantity                                   varchar(255)  COMMENT '仓位(数量）'
    ,available_quantity                                  varchar(255)  COMMENT '可用量'
    ,wait_check_up                                       varchar(255)  COMMENT '待检待上架量'
    ,wait_arrival_quantity                               varchar(255)  COMMENT '待到货量'
    ,difference                                          varchar(255)  COMMENT '差额'
    ,packaging_specifications                            varchar(255)  COMMENT '包装规格（cm）'
    ,box_gauge                                           varchar(255)  COMMENT '箱规（cm）'
    ,cbm                                                 varchar(255)  COMMENT 'CBM（m³）'
    ,volume_weight                                       varchar(255)  COMMENT '体积重（kg）'
    ,one_net_weight                                      varchar(255) COMMENT '单品净重（g）'
    ,one_gross_weight                                    varchar(255) COMMENT '单品毛重（g）'
    ,total_net_weight                                    varchar(255) COMMENT '总净重（kg）'
    ,total_gross_weight                                  varchar(255) COMMENT '总毛重（kg）'
    ,notes                                               varchar(255)  COMMENT '备注'
    ,inventory_lock_status                               varchar(255)  COMMENT '库存锁定状态'
    ,create_user                                         varchar(255)  COMMENT '创建用户'
    ,data_create_time                                    varchar(255)  COMMENT '创建时间'
    ,one_box_net_weight                                  varchar(255)  COMMENT '单箱净重（kg）'
    ,one_box_gross_weight                                varchar(255)  COMMENT '单箱毛重（kg）'
    ,create_time                                         datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
    ,modify_time                                         datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
    ,data_status                                         varchar(255) COMMENT '数据状态'
    ,data_number                                         int          COMMENT '单位数据量'
    ,batch_number                                        varchar(255) COMMENT '批次号'
    ,execute_log                                         varchar(2000) COMMENT '接口执行日志'
    ,PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='发货档案_发货单_发货计划';

--加工计划_采购-单品明细-------------------------------------------------------------------------------------------------------------------------------------------------------------------
create table sharkbox_merge.lingxing_purchase_processing_plan(
     id                                                  varchar(255)  COMMENT '加工计划号+单品SKU'
    ,data_owner                                          varchar(255)  COMMENT '数据属主'
    ,processing_plan_number                              varchar(255)  COMMENT '加工计划号'
    ,warehouse                                           varchar(255)  COMMENT '仓库'
    ,combination_product_name                            varchar(255)  COMMENT '组合品名'
    ,combination_sku                                     varchar(255)  COMMENT '组合SKU'
    ,product_label                                       varchar(255)  COMMENT '产品标签'
    ,combination_store                                   varchar(255)  COMMENT '组合店铺'
    ,combination_fnsku                                   varchar(255)  COMMENT '组合FNSKU'
    ,combination_msku                                    varchar(255)  COMMENT '组合MSKU'
    ,purchase_number                                     varchar(255)  COMMENT '采购单号'
    ,product_name                                        varchar(255)  COMMENT '单品品名'
    ,sku                                                 varchar(255)  COMMENT '单品SKU'
    ,combination_ratio                                   varchar(255)  COMMENT '组合比例'
    ,planned_procurement_quantity                        varchar(255)  COMMENT '计划采购量'
    ,actual_procurement_quantity                         varchar(255)  COMMENT '实际采购量'
    ,planned_processing_volume                           varchar(255)  COMMENT '单品计划加工量'
    ,pre_lock_quantity                                   varchar(255)  COMMENT '预锁定量'
    ,available_lock_quantity_purchase                    varchar(255)  COMMENT '可用锁定量（采购）'
    ,available_lock_quantity_warehouse                   varchar(255)  COMMENT '可用锁定量（仓库）'
    ,processing_in_progress                              varchar(255)  COMMENT '加工中'
    ,processed                                           varchar(255)  COMMENT '已加工'
    ,expected_arrived_quantity                           varchar(255)  COMMENT '单品预计到货时间'
    ,create_time                                         datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
    ,modify_time                                         datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
    ,data_status                                         varchar(255) COMMENT '数据状态'
    ,data_number                                         int          COMMENT '单位数据量'
    ,batch_number                                        varchar(255) COMMENT '批次号'
    ,execute_log                                         varchar(2000) COMMENT '接口执行日志'
    ,PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='加工计划_采购-单品明细';

/*
--发货档案_发货单_发货单详情-------------------------------------------------------------------------------------------------------------------------------------------------------------------
drop table if exists sharkbox_merge.lingxing_shipping_document_details;
create table sharkbox_merge.lingxing_shipping_document_details(
     id                                                  varchar(255) COMMENT '发货单号+SKU'
    ,group_id                                            varchar(255) COMMENT '组id'
    ,data_owner                                          varchar(255) COMMENT '数据属主'
    ,shipping_order_number                               varchar(255) COMMENT '发货单号'
    ,shipping_warehouse_documents                        varchar(255) COMMENT '发货仓库（单据）'
    ,factory_direct_delivery                             varchar(255) COMMENT '工厂直发'
    ,logistics_center_code                               varchar(255) COMMENT '物流中心编码'
    ,creater                                             varchar(255) COMMENT '创建人'
    ,creation_time                                       varchar(255) COMMENT '创建时间'
    ,shipper                                             varchar(255) COMMENT '发货人'
    ,delivery_time                                       varchar(255) COMMENT '发货时间'
    ,actual_delivery_time                                varchar(255) COMMENT '实际发货时间'
    ,person_in_charge                                    varchar(255) COMMENT '负责人'
    ,document_remarks                                    varchar(255) COMMENT '备注(单据)'
    ,invoice_status                                      varchar(255) COMMENT '发货单状态'
    ,print_status                                        varchar(255) COMMENT '打印状态'
    ,mode_of_transport                                   varchar(255) COMMENT '运输方式'
    ,logistics_provider                                  varchar(255) COMMENT '物流商'
    ,logistics_channels                                  varchar(255) COMMENT '物流渠道'
    ,logistics_provider_tracking_number                  varchar(255) COMMENT '物流商单号'
    ,estimated_total_cost                                varchar(255) COMMENT '预估总费用'
    ,estimated_logistics_costs                           varchar(255) COMMENT '预估物流费用'
    ,estimate_other_expenses                             varchar(255) COMMENT '预估其他费用'
    ,actual_total_cost                                   varchar(255) COMMENT '实际总费用'
    ,actual_logistics_costs                              varchar(255) COMMENT '实际物流费用'
    ,actual_other_expenses                               varchar(255) COMMENT '实际其他费用'
    ,query_number                                        varchar(255) COMMENT '查询单号'
    ,expected_logistics_delivery_time                    varchar(255) COMMENT '物流预计时效'
    ,expected_delivery_time                              varchar(255) COMMENT '预计到货时间'
    ,order_logistics_status                              varchar(255) COMMENT '订单物流状态'
    ,vat_tax_id                                          varchar(255) COMMENT 'VAT税号'
    ,allocation_method                                   varchar(255) COMMENT '分摊方式'
    ,is_split_calculation                                varchar(255) COMMENT '是否分抛计算'
    ,split_coefficient                                   varchar(255) COMMENT '分抛系数'
    ,image                                               varchar(255) COMMENT '图片'
    ,product_name                                        varchar(255) COMMENT '品名'
    ,sku                                                 varchar(255) COMMENT 'SKU'
    ,identification_code                                 varchar(255) COMMENT '识别码'
    ,declaration_quantity_related                        varchar(255) COMMENT '申报量(关联量)'
    ,store                                               varchar(255) COMMENT '店铺'
    ,country                                             varchar(255) COMMENT '国家'
    ,msku                                                varchar(255) COMMENT 'MSKU'
    ,fnsku                                               varchar(255) COMMENT 'FNSKU'
    ,asin                                                varchar(255) COMMENT 'ASIN'
    ,father_asin                                         varchar(255) COMMENT '父ASIN'
    ,planned_shipment_quantity                           varchar(255) COMMENT '计划发货量'
    ,plan_number                                         varchar(255) COMMENT '计划编号'
    ,shipment_plan_batch_number                          varchar(255) COMMENT '发货计划批次号'
    ,packaging_specifications                            varchar(255) COMMENT '包装规格'
    ,one_net_weight                                      varchar(255) COMMENT '单品净重'
    ,one_gross_weight                                    varchar(255) COMMENT '单品毛重'
    ,total_gross_weight                                  varchar(255) COMMENT '总毛重'
    ,total_net_weight                                    varchar(255) COMMENT '总净重'
    ,taxation                                            varchar(255) COMMENT '税费'
    ,packaging_type                                      varchar(255) COMMENT '包装类型'
    ,shipment_number                                     varchar(255) COMMENT '货件单号'
    ,deliver_amount                                      varchar(255) COMMENT '发货量'
    ,unit_fba_storage_cost                               varchar(255) COMMENT '单位FBA仓入库成本'
    ,unit_auxiliary_material_cost                        varchar(255) COMMENT '单位辅料费用'
    ,value_source                                        varchar(255) COMMENT '取值来源'
    ,unit_first_cost                                     varchar(255) COMMENT '单位头程费用'
    ,remarks_document_details                            varchar(255) COMMENT '备注(单据明细)'
    ,available_quantity                                  varchar(255) COMMENT '可用量'
    ,wait_check_up                                       varchar(255) COMMENT '待检待上架量'
    ,wait_arrival_quantity                               varchar(255) COMMENT '待到货量'
    ,difference                                          varchar(255) COMMENT '差额'
    ,shipment_status                                     varchar(255) COMMENT '货件状态'
    ,unit_outbound_first_cost                            varchar(255) COMMENT '单位出库头程费用'
    ,unit_taxes                                          varchar(255) COMMENT '单位税费'
    ,unit_outbound_cost                                  varchar(255) COMMENT '单位出库费用'
    ,purchase_unit_price                                 varchar(255) COMMENT '采购单价'
    ,purchase_unit_price_since                           varchar(255) COMMENT '采购单价(自定义)'
    ,unit_outbound_cost_since                            varchar(255) COMMENT '单位出库费用(自定义)'
    ,unit_auxiliary_material_cost_since                  varchar(255) COMMENT '单位辅料费用(自定义)'
    ,unit_outbound_first_since                           varchar(255) COMMENT '单位出库头程(自定义)'
    ,unit_fba_storage_cost_since                         varchar(255) COMMENT '单位FBA仓入库成本(自定义)'
    ,product_url                                         varchar(255) COMMENT '产品链接'
    ,shipping_warehouse_document_details                 varchar(255) COMMENT '发货仓库（单据明细）'
    ,shipping_warehouse_store                            varchar(255) COMMENT '发货仓库店铺'
    ,shipping_warehouse_fnsku                            varchar(255) COMMENT '发货仓库FNSKU'
    ,transfer_quantity                                   varchar(255) COMMENT '调出量'
    ,position_quantity                                   varchar(255) COMMENT '仓位（数量）'
    ,purchase_order_quantity                             varchar(255) COMMENT '采购单（关联量）'
    ,create_time                                         datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
    ,modify_time                                         datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
    ,data_status                                         varchar(255) COMMENT '数据状态'
    ,data_number                                         int          COMMENT '单位数据量'
    ,batch_number                                        varchar(255) COMMENT '批次号'
    ,PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='发货档案_发货单_发货单详情';
*/



